apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-deployment
  name: notification-service
  namespace: ckad
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8091
  selector:
    app: notification-deployment
